spring:
  servlet:
    multipart:
      max-file-size: 1073741824
      max-request-size: 1073741824
      enabled: true
  application:
    name: WonderFileManageRepository
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:${application.keycloak-url}/realms/${application.realm}}
          jwk-set-uri: ${OAUTH2_JWK:${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs}


server:
#  servlet:
#    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8888}
  address: 0.0.0.0
  tomcat:
    basedir: C:/Java
application:
  realm: wonder
  keycloak-url: ${KEYCLOAK_URL:https://keycloak-3gn7q5gs6q-lm.a.run.app}
  client-id: wonder
  config:
    bucket-name: w-bucker
    max-upload-count: 1000 #Max 1000 files in an upload
    max-request-size: ${MAX_REQUEST_SIZE:1073741824}  #1gb
    max-in-mem-size: ${MAX_IN_MEM_SIZE:1073741824}  #1gb
